name: Nightly build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Checkout meilisearch/MeiliSearch
      run: git clone https://github.com/meilisearch/MeiliSearch.git /tmp/MeiliSearch

    - name: Get REVISION
      run: |
        cd /tmp/MeiliSearch
        echo $(git rev-list --count HEAD) > /tmp/revision
        cat /tmp/revision
    
    #::set-env 
    - run: echo ::set-output name=number::$(cat /tmp/revision)
      id: revision

    - name: Build tag
      run: |
        cd /tmp/MeiliSearch
        docker build -t meilisearch:${{ steps.revision.outputs.number }} .

    - name: Tag :latest
      run: |
        cd /tmp/MeiliSearch
        docker tag meilisearch:${{ steps.revision.outputs.number }} meilisearch:latest

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push tag to docker hub
      uses: actions-hub/docker@master
      with:
        args: push tadeugr/meilisearch:${{ steps.revision.outputs.number }}

    - name: Push latest to docker hub
      uses: actions-hub/docker@master
      with:
        args: push tadeugr/meilisearch:latest
