name: Nightly build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Checkout meilisearch/MeiliSearch
      run: git clone https://github.com/meilisearch/MeiliSearch.git /tmp/MeiliSearch

    - name: Get REVISION
      run: |
        cd /tmp/MeiliSearch
        echo $(git rev-list --count HEAD) > /tmp/revision
        cat /tmp/revision
     
    - run: echo ::set-output name=number::$(cat /tmp/revision)
      id: revision

    - run: echo ${{ steps.revision.outputs.number }}
      
    - uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: ${{ steps.revision.outputs.number }}
        
    #- name: set environment variables
    #    uses: allenevans/set-env@v1.0.0
    #    with:
    #      REVISION: echo $(cat /tmp/revision)

    #- name: Printenv
    #    run: |
    #      echo "REVISION=${REVISION}"
    #      printenv

    - name: Build tag
      run: |
        cd /tmp/MeiliSearch
        docker build -t meilisearch:$(cat /tmp/revision) .

    - name: Tag :latest
      run: |
        cd /tmp/MeiliSearch
        docker tag meilisearch:$(cat /tmp/revision) meilisearch:latest

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push tag to docker hub
      uses: actions-hub/docker@master
      with:
        args: push meilisearch:$(cat /tmp/revision)

    - name: Push latest to docker hub
      uses: actions-hub/docker@master
      with:
        args: push meilisearch:latest
