name: Nightly build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Fetch upstream
      run: |
        git remote add upstream https://github.com/meilisearch/MeiliSearch.git
        git fetch upstream
        git pull upstream master

    - name: Get REVISION
      run: |
        echo $(git rev-list --count HEAD) > /tmp/revision
        cat /tmp/revision
    
    #::set-env 
    - name: Set revision variable
      run: echo ::set-output name=number::$(cat /tmp/revision)
      id: revision

    - name: Build tag
      run: |
        docker build -t tadeugr/meilisearch:${{ steps.revision.outputs.number }} .

    - name: Tag :latest
      run: |
        docker tag tadeugr/meilisearch:${{ steps.revision.outputs.number }} tadeugr/meilisearch:latest

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push tag to docker hub
      uses: actions-hub/docker@master
      with:
        args: push tadeugr/meilisearch:${{ steps.revision.outputs.number }}

    - name: Push latest to docker hub
      uses: actions-hub/docker@master
      with:
        args: push tadeugr/meilisearch:latest
